#include <curl/curl.h>
#include <stdlib.h>
#include <string.h>

// workaround for older versions of libcurl
#ifndef CURL_SSLVERSION_TLSv1_3
  #define CURL_SSLVERSION_TLSv1_3 7
#endif

#define GET_VAR(NAME) long get_ ## NAME (){return NAME;}
GET_VAR(CURL_GLOBAL_ALL)
GET_VAR(CURLOPT_URL)
GET_VAR(CURLOPT_VERBOSE)
GET_VAR(CURLOPT_WRITEFUNCTION)
GET_VAR(CURLOPT_WRITEDATA)
GET_VAR(CURLOPT_HTTPHEADER)
GET_VAR(CURLOPT_POSTFIELDS)
GET_VAR(CURLOPT_FOLLOWLOCATION)
GET_VAR(CURLINFO_RESPONSE_CODE)
GET_VAR(CURLOPT_ERRORBUFFER)
GET_VAR(CURLOPT_SSLVERSION)
GET_VAR(CURL_SSLVERSION_DEFAULT)
GET_VAR(CURL_SSLVERSION_TLSv1)
GET_VAR(CURL_SSLVERSION_SSLv2)
GET_VAR(CURL_SSLVERSION_SSLv3)
GET_VAR(CURL_SSLVERSION_TLSv1_0)
GET_VAR(CURL_SSLVERSION_TLSv1_1)
GET_VAR(CURL_SSLVERSION_TLSv1_2)
GET_VAR(CURL_SSLVERSION_TLSv1_3)
GET_VAR(CURLOPT_CAINFO)
