name: Trigger Concourse on Pull Request
on: [ pull_request, workflow_dispatch ]
env:
  HOST: https://ci.jitx.com
  TEAM: main
  PIPELINE: stanzaenv
  INSTVARS: vars.branch="${{ github.base_ref }}"
  TOKEN: ${{ secrets.CONCOURSE_WEBHOOK_TOKEN }}
jobs:
  trigger-pr:
    runs-on: ubuntu-latest
    env:
      RESOURCE: github--stanzaenv--pr
    steps:
      - name: Trigger Concourse Pull Request
        run: |
          URL="${HOST}/api/v1/teams/${TEAM}/pipelines/${PIPELINE}/resources/${RESOURCE}/check/webhook?webhook_token=${TOKEN}"
          echo Triggering: "${URL}"
          curl --silent --fail --show-error --location --request "POST" --url "${URL}"
